import { readdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface AutoCorpusStatus {
  enablement: {
    promote: boolean;
    promoteDailyQuota: number;
    minConfidence: number;
    threatResearchAuto: boolean;
    threatResearchMaxPerHour: number;
    learnedRulesPromote: boolean;
    learnedRulesMinConfidence: number;
    instantLearning: boolean;
  };
  corpusStats: {
    totalFixtures: number;
    attackCategories: number;
    lastPromotedAt: string | null;
    promotionsToday: number;
    promotionsThisWeek: number;
    perCategory: Record<string, { total: number; autoGenerated: number; lastGenerated: string | null }>;
  };
  threatResearch: {
    lastRunAt: string | null;
    discoveriesToday: number;
    discoveriesThisWeek: number;
    bypassesDetected: number;
    confidenceAvg: number;
    queueDepth: number;
  };
}

export function getAutoCorpusStatus(): AutoCorpusStatus {
  const now = Date.now();
  const dayStart = new Date(new Date().toDateString()).getTime();

  const enablement: AutoCorpusStatus['enablement'] = {
    promote: process.env['MASTYF_AI_AUTO_CORPUS_PROMOTE'] === 'true',
    promoteDailyQuota: parseInt(process.env['MASTYF_AI_AUTO_CORPUS_MAX_PER_DAY'] || '5', 10),
    minConfidence: parseFloat(process.env['MASTYF_AI_AUTO_CORPUS_MIN_CONFIDENCE'] || '0.90'),
    threatResearchAuto: process.env['MASTYF_AI_THREAT_RESEARCH_AUTO'] === 'true',
    threatResearchMaxPerHour: parseInt(process.env['MASTYF_AI_THREAT_RESEARCH_MAX_PER_HOUR'] || '20', 10),
    learnedRulesPromote: process.env['MASTYF_AI_LEARNED_RULES_PROMOTE'] === 'true',
    learnedRulesMinConfidence: parseFloat(process.env['MASTYF_AI_LEARNED_RULES_MIN_CONFIDENCE'] || '0.90'),
    instantLearning: process.env['MASTYF_AI_AI_INSTANT_LEARNING'] === 'true',
  };

  const corpusAttacksDir = join(process.cwd(), 'corpus', 'attacks');
  const perCategory: AutoCorpusStatus['corpusStats']['perCategory'] = {};
  let totalFixtures = 0;
  let attackCategories = 0;
  let promotionsToday = 0;
  let promotionsThisWeek = 0;
  let lastPromotedAt: string | null = null;

  if (existsSync(corpusAttacksDir)) {
    for (const cat of readdirSync(corpusAttacksDir, { withFileTypes: true })) {
      if (!cat.isDirectory()) continue;
      attackCategories++;
      const catDir = join(corpusAttacksDir, cat.name);
      const files = readdirSync(catDir).filter(f => f.endsWith('.json'));
      totalFixtures += files.length;

      let autoGenerated = 0;
      let catLast: string | null = null;
      for (const f of files) {
        try {
          const content = JSON.parse(readFileSync(join(catDir, f), 'utf-8'));
          if (content._generated || content._auto || f.includes('-gen-') || content._simulates) {
            autoGenerated++;
          }
        } catch {}
      }

      perCategory[cat.name] = { total: files.length, autoGenerated, lastGenerated: catLast };
    }
  }

  const manifestPath = join(process.cwd(), 'corpus', 'auto-corpus-manifest.json');
  if (existsSync(manifestPath)) {
    try {
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
      const entries = manifest.entries || manifest.promotions || [];
      const weekAgo = now - 7 * 86400000;
      promotionsToday = entries.filter((e: any) => new Date(e.promotedAt || e.timestamp).getTime() > dayStart).length;
      promotionsThisWeek = entries.filter((e: any) => new Date(e.promotedAt || e.timestamp).getTime() > weekAgo).length;
      if (entries.length > 0) {
        const last = entries[entries.length - 1];
        lastPromotedAt = last.promotedAt || last.timestamp || null;
      }
    } catch {}
  }

  const threatStatePath = join(process.env['HOME'] || '/tmp', '.mastyf-ai', 'threat-research-state.json');
  let discoveriesToday = 0;
  let discoveriesThisWeek = 0;
  let bypassesDetected = 0;
  let confidenceAvg = 0;
  let queueDepth = 0;
  let lastRunAt: string | null = null;

  if (existsSync(threatStatePath)) {
    try {
      const state = JSON.parse(readFileSync(threatStatePath, 'utf-8'));
      const weekAgo = now - 7 * 86400000;
      const items = state.discoveries || state.records || [];
      discoveriesToday = items.filter((i: any) => new Date(i.createdAt || i.timestamp).getTime() > dayStart).length;
      discoveriesThisWeek = items.filter((i: any) => new Date(i.createdAt || i.timestamp).getTime() > weekAgo).length;
      bypassesDetected = items.filter((i: any) => i.type === 'bypass').length;
      if (items.length > 0) {
        confidenceAvg = items.reduce((s: number, i: any) => s + (i.confidence || 0), 0) / items.length;
        lastRunAt = items[items.length - 1].createdAt || items[items.length - 1].timestamp || null;
      }
      queueDepth = state.pendingCount || state.queueDepth || 0;
    } catch {}
  }

  return {
    enablement,
    corpusStats: {
      totalFixtures,
      attackCategories,
      lastPromotedAt,
      promotionsToday,
      promotionsThisWeek,
      perCategory,
    },
    threatResearch: {
      lastRunAt,
      discoveriesToday,
      discoveriesThisWeek,
      bypassesDetected,
      confidenceAvg: Math.round(confidenceAvg * 100) / 100,
      queueDepth,
    },
  };
}
