'use client';

import { useEffect, useState, useCallback } from 'react';

interface AutoCorpusStatus {
  enablement: {
    promote: boolean;
    promoteDailyQuota: number;
    minConfidence: number;
    threatResearchAuto: boolean;
    threatResearchMaxPerHour: number;
    learnedRulesPromote: boolean;
    learnedRulesMinConfidence: number;
    instantLearning: boolean;
  };
  corpusStats: {
    totalFixtures: number;
    attackCategories: number;
    lastPromotedAt: string | null;
    promotionsToday: number;
    promotionsThisWeek: number;
    perCategory: Record<string, { total: number; autoGenerated: number; lastGenerated: string | null }>;
  };
  threatResearch: {
    lastRunAt: string | null;
    discoveriesToday: number;
    discoveriesThisWeek: number;
    bypassesDetected: number;
    confidenceAvg: number;
    queueDepth: number;
  };
}

interface ManifestEntry {
  advId: string;
  category: string;
  confidence: number;
  source: string;
  createdAt: string;
  status?: string;
}

export default function AutoCorpusControlPanel() {
  const [status, setStatus] = useState<AutoCorpusStatus | null>(null);
  const [entries, setEntries] = useState<ManifestEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState('');

  const load = useCallback(async () => {
    try {
      const [statusRes, manifestRes] = await Promise.all([
        fetch('/api/ai/auto-corpus/status'),
        fetch('/api/ai/auto-corpus/manifest?status=pending&limit=50'),
      ]);
      if (statusRes.ok) {
        const data = await statusRes.json();
        setStatus(data);
      }
      if (manifestRes.ok) {
        const data = await manifestRes.json();
        setEntries(data.entries || []);
      }
      setError(null);
    } catch (err) {
      if (err instanceof Error && !err.message.includes('abort')) {
        setError(err instanceof Error ? err.message : 'Failed to load');
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
    const interval = setInterval(load, 15000);
    return () => clearInterval(interval);
  }, [load]);

  const onApprove = async (advId: string) => {
    setBusy(`approve:${advId}`);
    try {
      const res = await fetch('/api/ai/auto-corpus/approve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ advId }),
      });
      if (res.ok) await load();
    } catch { /* ignore */ }
    setBusy('');
  };

  const onReject = async (advId: string) => {
    setBusy(`reject:${advId}`);
    try {
      const res = await fetch('/api/ai/auto-corpus/reject', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ advId }),
      });
      if (res.ok) await load();
    } catch { /* ignore */ }
    setBusy('');
  };

  const onApproveAll = async () => {
    setBusy('approve-all');
    try {
      const res = await fetch('/api/ai/auto-corpus/approve-bulk', { method: 'POST' });
      if (res.ok) await load();
    } catch { /* ignore */ }
    setBusy('');
  };

  const onRunResearch = async () => {
    setBusy('research');
    try {
      const res = await fetch('/api/threat-discovery/auto-research/run', { method: 'POST' });
      const data = await res.json();
      if (data.jobId) {
        alert('Auto Research started -- job ' + data.jobId);
      } else {
        alert(data.error || 'Failed to start Auto Research');
      }
      await load();
    } catch { /* ignore */ }
    setBusy('');
  };

  if (loading) {
    return (
      <div className="panel" style={{ marginTop: 'var(--space-6)' }}>
        <div className="panel-body">
          <p className="text-sm text-muted">Loading auto-corpus status...</p>
        </div>
      </div>
    );
  }

  if (error || !status) {
    return (
      <div className="panel" style={{ marginTop: 'var(--space-6)' }}>
        <div className="panel-body">
          <div className="banner banner-warning">
            Auto-corpus data unavailable. Enable with MASTYF_AI_AUTO_CORPUS_PROMOTE=true and MASTYF_AI_THREAT_RESEARCH_AUTO=true.
          </div>
        </div>
      </div>
    );
  }

  const { enablement, corpusStats, threatResearch } = status;
  const pending = entries.filter(e => !e.status || e.status === 'pending');

  const underrepresented = Object.entries(corpusStats.perCategory)
    .sort(([, a], [, b]) => a.total - b.total)
    .filter(([, stats]) => stats.total < 10)
    .slice(0, 6);

  return (
    <div className="panel" style={{ marginTop: 'var(--space-6)' }}>
      <div className="panel-header">
        <h2 className="panel-title">Autonomous Corpus Expansion</h2>
        <p className="text-sm text-muted">Self-improving attack corpus powered by local LLM (Ollama). Every blocked tool call feeds into a continuous discovery, validation, and promotion pipeline.</p>
      </div>
      <div className="panel-body">
        <div className="kpi-grid" style={{ marginBottom: 'var(--space-4)' }}>
          <div className="kpi-card">
            <div className="kpi-label">Total Fixtures</div>
            <div className="kpi-value">{corpusStats.totalFixtures}</div>
            <div className="kpi-secondary text-xs text-muted">{corpusStats.attackCategories} categories</div>
          </div>
          <div className="kpi-card">
            <div className="kpi-label">Promoted Today</div>
            <div className="kpi-value">{corpusStats.promotionsToday}</div>
            <div className="kpi-secondary text-xs text-muted">quota: {enablement.promoteDailyQuota === 0 ? 'unlimited' : enablement.promoteDailyQuota}/day</div>
          </div>
          <div className="kpi-card">
            <div className="kpi-label">Pending Review</div>
            <div className="kpi-value" style={{ color: pending.length > 0 ? 'var(--warning)' : 'var(--text-muted)' }}>{pending.length}</div>
          </div>
          <div className="kpi-card">
            <div className="kpi-label">LLM Confidence</div>
            <div className="kpi-value">{threatResearch.confidenceAvg || '--'}</div>
            <div className="kpi-secondary text-xs text-muted">{threatResearch.discoveriesToday} discoveries today</div>
          </div>
          <div className="kpi-card">
            <div className="kpi-label">Scheduler</div>
            <div className="kpi-value">
              <span className={`badge ${enablement.threatResearchAuto ? 'badge-success' : 'badge-neutral'}`}>
                {enablement.threatResearchAuto ? 'Active' : 'Idle'}
              </span>
            </div>
          </div>
        </div>

        <div className="grid grid-12" style={{ gap: 'var(--space-4)' }}>
          <div className="col-span-8">
            <div className="card">
              <div className="card-header">
                <span className="card-title">Pipeline Control</span>
              </div>
              <div className="card-body">
                <div className="flex gap-2 flex-wrap" style={{ marginBottom: 'var(--space-3)' }}>
                  <button
                    type="button"
                    className="btn btn-primary btn-sm"
                    onClick={onRunResearch}
                    disabled={busy === 'research'}
                  >
                    {busy === 'research' ? 'Starting...' : 'Run Auto Research'}
                  </button>
                </div>
                <div className="flex gap-2 items-center flex-wrap text-sm">
                  <span>Promoter:</span>
                  <span className={`badge ${enablement.promote ? 'badge-success' : 'badge-neutral'}`}>
                    {enablement.promote ? 'ON' : 'OFF'}
                  </span>
                  <span>Learning:</span>
                  <span className={`badge ${enablement.learnedRulesPromote ? 'badge-success' : 'badge-neutral'}`}>
                    {enablement.learnedRulesPromote ? 'ON' : 'OFF'}
                  </span>
                  <span>Instant:</span>
                  <span className={`badge ${enablement.instantLearning ? 'badge-success' : 'badge-neutral'}`}>
                    {enablement.instantLearning ? 'ON' : 'OFF'}
                  </span>
                </div>
                {corpusStats.lastPromotedAt && (
                  <p className="text-xs text-muted" style={{ marginTop: 'var(--space-2)' }}>
                    Last promotion: {new Date(corpusStats.lastPromotedAt).toLocaleString()} |
                    This week: {corpusStats.promotionsThisWeek}
                    {threatResearch.lastRunAt && ` | Last discovery: ${new Date(threatResearch.lastRunAt).toLocaleString()}`}
                  </p>
                )}
              </div>
            </div>

            <div className="card" style={{ marginTop: 'var(--space-4)' }}>
              <div className="card-header flex justify-between items-center">
                <span className="card-title">Pending Review</span>
                {pending.length > 0 && (
                  <button
                    type="button"
                    className="btn btn-primary btn-sm"
                    onClick={onApproveAll}
                    disabled={busy === 'approve-all'}
                  >
                    {busy === 'approve-all' ? 'Approving...' : `Approve All (${pending.length})`}
                  </button>
                )}
              </div>
              <div className="card-body">
                {entries.length === 0 ? (
                  <div className="empty-state" style={{ padding: 'var(--space-5)' }}>
                    <p className="empty-state-title">No entries awaiting review</p>
                    <p className="empty-state-desc">
                      Auto-corpus entries will appear here as the LLM generates new attack payloads.
                      Run Auto Research to kick off a discovery cycle, or wait for the scheduler to process blocked calls.
                    </p>
                  </div>
                ) : (
                  <div className="table-wrap">
                    <table className="table table-compact">
                      <thead>
                        <tr>
                          <th>Entry</th>
                          <th>Category</th>
                          <th>Confidence</th>
                          <th>Source</th>
                          <th>Created</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {entries.map((e) => (
                          <tr key={e.advId}>
                            <td><code className="text-xs mono">{e.advId}</code></td>
                            <td className="text-sm">{e.category}</td>
                            <td>
                              <span className={`badge ${e.confidence >= 0.9 ? 'badge-success' : e.confidence >= 0.8 ? 'badge-warning' : 'badge-danger'}`}>
                                {e.confidence.toFixed(2)}
                              </span>
                            </td>
                            <td className="text-sm">{e.source}</td>
                            <td className="text-sm">{new Date(e.createdAt).toLocaleDateString()}</td>
                            <td>
                              <div className="flex gap-2">
                                <button
                                  type="button"
                                  className="btn btn-ghost btn-sm"
                                  onClick={() => onApprove(e.advId)}
                                  disabled={busy === `approve:${e.advId}`}
                                >
                                  {busy === `approve:${e.advId}` ? '...' : 'Approve'}
                                </button>
                                <button
                                  type="button"
                                  className="btn btn-ghost btn-sm"
                                  onClick={() => onReject(e.advId)}
                                  disabled={busy === `reject:${e.advId}`}
                                >
                                  {busy === `reject:${e.advId}` ? '...' : 'Reject'}
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="col-span-4" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
            <div className="card">
              <div className="card-header">
                <span className="card-title">Underrepresented Categories</span>
              </div>
              <div className="card-body">
                {underrepresented.length === 0 ? (
                  <p className="text-sm text-muted">All categories have sufficient coverage.</p>
                ) : (
                  underrepresented.map(([cat, stats]) => (
                    <div key={cat} className="flex justify-between items-center" style={{ padding: 'var(--space-1) 0', borderBottom: '1px solid var(--border)' }}>
                      <span className="text-sm">{cat}</span>
                      <span className="text-xs mono" style={{ color: stats.total < 5 ? 'var(--danger)' : 'var(--warning)' }}>
                        {stats.total} entries
                        {stats.autoGenerated > 0 && ` (+${stats.autoGenerated})`}
                      </span>
                    </div>
                  ))
                )}
              </div>
            </div>

            <div className="card">
              <div className="card-header">
                <span className="card-title">Threat Research</span>
              </div>
              <div className="card-body">
                <div style={{ display: 'grid', gap: 'var(--space-2)' }}>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted">Bypasses Detected</span>
                    <span>{threatResearch.bypassesDetected}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted">Queue Depth</span>
                    <span>{threatResearch.queueDepth}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted">Max/Hour</span>
                    <span>{enablement.threatResearchMaxPerHour}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted">Min Confidence</span>
                    <span>{enablement.minConfidence}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
