'use client';

import { useEffect, useState } from 'react';

interface AutoCorpusStatus {
  enablement: {
    promote: boolean;
    promoteDailyQuota: number;
    minConfidence: number;
    threatResearchAuto: boolean;
    threatResearchMaxPerHour: number;
    learnedRulesPromote: boolean;
    learnedRulesMinConfidence: number;
    instantLearning: boolean;
  };
  corpusStats: {
    totalFixtures: number;
    attackCategories: number;
    lastPromotedAt: string | null;
    promotionsToday: number;
    promotionsThisWeek: number;
    perCategory: Record<string, { total: number; autoGenerated: number }>;
  };
  threatResearch: {
    lastRunAt: string | null;
    discoveriesToday: number;
    discoveriesThisWeek: number;
    bypassesDetected: number;
    confidenceAvg: number;
    queueDepth: number;
  };
}

function statusBadge(active: boolean): string {
  return active ? '🟢 Active' : '⚫ Idle';
}

export default function AutoCorpusPanel() {
  const [status, setStatus] = useState<AutoCorpusStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch('/api/ai/auto-corpus/status');
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        if (!cancelled) { setStatus(data); setLoading(false); }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load');
          setLoading(false);
        }
      }
    }
    load();
    const interval = setInterval(load, 15000);
    return () => { cancelled = true; clearInterval(interval); };
  }, []);

  if (loading) return <p className="muted">Loading auto-corpus status…</p>;
  if (error) return <p className="muted">Auto-corpus data unavailable — enable with MASTYF_AI_AUTO_CORPUS_PROMOTE=true</p>;
  if (!status) return null;

  const { enablement, corpusStats, threatResearch } = status;

  return (
    <div style={{ marginTop: 24 }}>
      <h3>🤖 Autonomous Corpus Expansion</h3>
      <p className="muted">Self-improving attack corpus powered by local LLM (Ollama). Every blocked tool call feeds into a continuous discovery → validation → promotion pipeline.</p>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 10, margin: '16px 0' }}>
        <div style={{ padding: 12, background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 8 }}>
          <div style={{ fontSize: 11, color: '#166534', fontWeight: 600 }}>Corpus Size</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#15803d' }}>{corpusStats.totalFixtures}</div>
          <div style={{ fontSize: 11, color: '#166534' }}>{corpusStats.attackCategories} categories</div>
        </div>
        <div style={{ padding: 12, background: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: 8 }}>
          <div style={{ fontSize: 11, color: '#1e40af', fontWeight: 600 }}>Promotions Today</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#2563eb' }}>{corpusStats.promotionsToday}</div>
          <div style={{ fontSize: 11, color: '#1e40af' }}>quota: {enablement.promoteDailyQuota}/day</div>
        </div>
        <div style={{ padding: 12, background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 8 }}>
          <div style={{ fontSize: 11, color: '#92400e', fontWeight: 600 }}>LLM Discoveries</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#d97706' }}>{threatResearch.discoveriesToday}</div>
          <div style={{ fontSize: 11, color: '#92400e' }}>avg confidence: {threatResearch.confidenceAvg}</div>
        </div>
        <div style={{ padding: 12, background: '#fce7f3', border: '1px solid #fbcfe8', borderRadius: 8 }}>
          <div style={{ fontSize: 11, color: '#9d174d', fontWeight: 600 }}>Bypasses Found</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#db2777' }}>{threatResearch.bypassesDetected}</div>
          <div style={{ fontSize: 11, color: '#9d174d' }}>queue: {threatResearch.queueDepth}</div>
        </div>
      </div>

      <div style={{ marginTop: 12, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        <div style={{ padding: 12, background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8 }}>
          <strong>Pipeline Status</strong>
          <div style={{ marginTop: 8, display: 'grid', gap: 4, fontSize: 13 }}>
            <div>{statusBadge(enablement.threatResearchAuto)} Threat Research</div>
            <div>{statusBadge(enablement.promote)} Corpus Promotion</div>
            <div>{statusBadge(enablement.learnedRulesPromote)} Rule Learning</div>
            <div>{statusBadge(enablement.instantLearning)} Instant Block Analysis</div>
          </div>
        </div>
        <div style={{ padding: 12, background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8 }}>
          <strong>Underrepresented Categories</strong>
          <div style={{ marginTop: 8, maxHeight: 160, overflowY: 'auto', fontSize: 12 }}>
            {Object.entries(corpusStats.perCategory)
              .sort(([, a], [, b]) => a.total - b.total)
              .slice(0, 8)
              .map(([cat, stats]) => (
                <div key={cat} style={{ display: 'flex', justifyContent: 'space-between', padding: '2px 0', borderBottom: '1px solid #f3f4f6' }}>
                  <span>{cat}</span>
                  <span style={{ fontFamily: 'monospace', color: stats.total < 10 ? '#dc2626' : stats.total < 20 ? '#d97706' : '#059669' }}>
                    {stats.total} entries {stats.autoGenerated > 0 ? `(+${stats.autoGenerated} auto)` : ''}
                  </span>
                </div>
              ))}
          </div>
        </div>
      </div>

      {corpusStats.lastPromotedAt && (
        <p className="muted" style={{ marginTop: 12, fontSize: 11 }}>
          Last promotion: {new Date(corpusStats.lastPromotedAt).toLocaleString()} · This week: {corpusStats.promotionsThisWeek}
          {threatResearch.lastRunAt && ` · Last discovery: ${new Date(threatResearch.lastRunAt).toLocaleString()}`}
        </p>
      )}
    </div>
  );
}
